name: Conformer
conformer_architecture:
  input_dim: ${feature_extractor.n_features}
  num_heads: 6
  ffn_dim: 128
  num_layers: 4
  depthwise_conv_kernel_size: 31
  dropout: 0.0
  use_group_norm: False
  convolution_first: False
out_channels: ${tokenizer.n_tokens}