name: CNN
architecture:
  in_channels: ${feature_extractor.n_features}
  hidden_channels: 100
  out_channels: ${tokenizer.n_tokens}
  kernel_size: 5
  num_res_blocks: null
  num_conv_blocks: 7
  p: 0.0
