model_dir: C:\Users\amita\PycharmProjects\asr_project\experiments\debug_model

defaults:
  - trainer: lightning
  - optimizer: adamW
  - model: naive_cnn
  - loss: ctc
  - data: an4
  - /feature_extractor@feature_extractor: mfcc
  - /tokenizer@tokenizer: convert
