cls:
  _target_: asr_project.data.feature_extractor.FeatureExtractor
  sample_rate: ${data.fs}
  n_mfcc: 13
  compute_deltas: True
  melkwargs:
    n_fft: 1000
    n_mels: 128
n_features: 36
name: MFCC
